ALTER TABLE groups ADD COLUMN default_currency TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE expenses ADD COLUMN currency TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE expenses ADD COLUMN exchange_rate NUMERIC NOT NULL DEFAULT 1;
